workflows:
  ios-build:
    name: iOS Build (IPA - Local Install)
    max_build_duration: 120
    instance_type: mac_mini_m1

    environment:
      groups:
        - codemagic
      vars:
        BUNDLE_ID: "com.sygecom.srm"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        EXPORT_METHOD: "development" # development ou ad-hoc
      node: 20.11.0
      xcode: latest
      cocoapods: default

    scripts:
      - name: Instalar dependências
        script: |
          npm ci

      - name: Gerar build estático do Nuxt
        script: |
          npm run generate

      - name: Sincronizar Capacitor iOS
        script: |
          npx cap sync ios

      - name: Instalar CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Archive iOS (gera .xcarchive)
        script: |
          xcodebuild archive \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath build/App.xcarchive \
            CODE_SIGN_STYLE=Automatic

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build/ipa

    artifacts:
      - build/ipa/*.ipa
      - build/App.xcarchive

    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false
